# This is a basic workflow to help you get started with Actions

name: Hello World


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
   hello-world:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

    
      - name: Run a multi-line script
        run: |
          echo Adiciona outras actions no build do projeto
          echo imprime linha separada
